### ISSUE TITLE
problem with virtuals

### ISSUE THREAD

**Issue by bonesoul** [disjunction/node-cache-manager-mongoose#4] opened 2017-01-21 17:48 UTC
Basically i'm caching data from my mongoose models which has some virtuals with them and model is defined with options;

 {
	toObject: { virtuals: true },
	toJSON: { virtuals: true }
});

The thing is that when i use memcache strore (https://github.com/theogravity/node-cache-manager-memcached-store), the cache data also contains those virtuals but node-cache-manager-mongoose somehow strips them from my data.

any ideas?

**Comment by bonesoul** [comment] 2017-01-21 17:52
an toJSON() call on data may fix the issue?

**Comment by bonesoul** [comment] 2017-02-01 18:47
any chances you can review this?

**Comment by disjunction** [comment] 2017-02-01 20:21
Hi @bonesoul, I acknowledge the problem, yet I had no time to make a fix. I'll probably look into it on weekend. Meanwhile you're welcome to contribute.

**Comment by disjunction** [comment] 2017-02-05 14:57
I checked how it works with memcached. In my test it did return the same object as I've just set and thus the function members persisted. But if you look into the cached values in memcache - you'll see only a standard JSON representation is saved. And as expected on the next run all functions were gone.

As far as I can see the cache-manager doesn't support caching objects with functions, which is a valid decision. So the behavior is a feature and not a bug. Closing the issue.

**Closed by disjunction** 2017-02-05 14:57 UTC

**Comment by bonesoul** [comment] 2017-02-05 20:01
No, memcache version just behaves all good with my data but your mongoose version doesn't hold them correctly.

**Comment by bonesoul** [comment] 2017-02-10 10:18
@disjunction mongoose virtuals are not functions, they are 'virtual' fields and i believe your decision is wrong there.
